---
- name: Commit device groups on Panorama
  hosts: all
  connection: local
  gather_facts: False

  vars:
    credentials:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"      

  collections:
    - paloaltonetworks.panos
    
  tasks:
    - name: commit device_groups
      panos_commit:
        provider: "{{ credentials }}"
        admins: ["{{ username }}"]
        device_group: "{{ item }}"
      loop: "{{ dg_list }}"
      loop_control:
        loop_var: item
      async: 360
      poll: 0
      register: commit_output
      
    - name: dump var
      debug:
        var: commit_output
