---
- name: Modify a PAN-OS security rule
  hosts: all
  connection: local
  gather_facts: False
  any_errors_fatal: true

  vars:
    credentials:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      
  collections:
   - paloaltonetworks.panos

  tasks:
  - name: Process the rule
    panos_security_rule:
      provider: '{{ credentials }}'
      device_group: '{{ rule_devicegroup }}'
      rule_name: '{{ rule_name }}'
      description: '{{ rule_description }}'
      source_zone: ['{{ rule_source_zone }}']
      source_ip: ['{{ rule_source_ip }}']
      source_user: ['{{ rule_source_user }}']
      hip_profiles: ['{{ rule_hip_profile }}']
      destination_zone: ['{{ rule_destination_zone }}']
      destination_ip: ['{{ rule_destination_ip }}']
      application: ['{{ rule_application }}']
      service: ['{{ rule_service }}']
      category: ['{{ rule_category }}']
      action: '{{ rule_action }}'
      group_profile: '{{ rule_secprofile }}'
      log_setting: '{{ rule_logprofile }}'
      state: '{{ rule_state }}'
      commit: False
  
  - name: Update the ServiceNow request
    snow_record:
      username: '{{ snow_username }}'
      password: '{{ snow_password }}'
      instance: '{{ snow_instance }}'
      table: '{{ snow_table }}'
      number: '{{ snow_request }}'
      state: present
      data:
        state: Closed Complete
